version: '3'
    
networks:
  traefik:
    external: true

services:
  openspeedtest:
    image: openspeedtest/${OPENSPEEDTEST_DOCKER_TAG:-latest}
    container_name: ${OPENSPEEDTEST_CONTAINER_NAME:-openspeedtest} 
    restart: ${OPENSPEEDTEST_RESTART:-unless-stopped}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    networks:
      - traefik
    labels:
      - joyride.host.name=${OPENSPEEDTEST_CONTAINER_NAME:-openspeedtest}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.entrypoints=websecure
      - traefik.http.routers.openspeedtest.rule=Host(`${OPENSPEEDTEST_CONTAINER_NAME:-openspeedtest}.${HOST_DOMAIN}`)
      #- traefik.http.services.openspeedtest.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.openspeedtest.loadbalancer.server.port=3000
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10000000000
      - traefik.http.routers.openspeedtest.middlewares=limit
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${OPENSPEEDTEST_FLAME_NAME:-openspeedtest} 
      - flame.url=https://${OPENSPEEDTEST_CONTAINER_NAME:-openspeedtest}.${HOST_DOMAIN}
      - flame.icon=${OPENSPEEDTEST_FLAME_ICON:-docker} # optional, default is "docker"
